### ISSUE TITLE
Added events/holidays for Semester 1 16-17

### ISSUE THREAD

**Issue by nakulbajaj** [HarkerDev/bellschedule#39]
9/30/16 Fall Break
10/31/16 Fall Break
11/21/16 PTC
11/22/16 PTC
11/23/16|11/25/16            Thanksgiving Break
12/13/16    F16 s1d1
12/14/16    F16 s1d2
12/15/16    F16 s1d3
12/16/16    F16 s1d4
12/17/16|1/3/17            Winter Break
1/16/17 MLK Day

**Comment by Andrew-Tierno** [comment]
Hi Nakul,

Did you want to make a commit to the site?

**Comment by nakulbajaj** [comment]
Hi Andrew,

Yes, I would like to help with the project over time. 

However, at the moment there is nothing urgent which I could change. (Other than the pull request I offered to add more Semester 1 holidays)

Thanks

**Comment by mananshah99** [comment]
Fixed in PR #40. Thanks!
